version: '3.8'

services:
  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service
    networks:
      - app-network

  node-service:
    build: 
      context: api
      dockerfile: Dockerfile
    environment:
      - "DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_HOST=${DB_HOST}"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    build: 
      context: db
      dockerfile: Dockerfile
    image: mariadb:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_HOST=${MYSQL_HOST}"
    ports:
      - "3306:3306"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
    networks:
      - app-network

networks:
  app-network:
